config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AppPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views
import users

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("swtich-hosting/", views.switch_hosting, name="switch-hosting"),
    path("swtich-language/", views.switch_language, name="switch-language"),
]

templates/mixins/room_card.html
<div class="w-1/4 mb-10 px-2 overflow-hidden">
    <a href="{% url 'rooms:detail' room.pk %}">
        <div class="w-full h-64 rounded-xl bg-cover bg-center mb-2" style="background-image: url({{room.first_photo}});"></div>
        <div class="flex justify-between mb-2 truncate">
            <div class="w-4/5 overflow-hidden flex">
                {% if room.host.superhost %}
                    <span class="mr-2 uppercase font-medium text-xs border border-black text-black rounded px-1">superhost</span>   
                {% endif %}
                <span class="text-sm text-gray-600 block truncate">{{room.city}}, {{room.country.name}}</span>
            </div>
            <span class="text-sm flex items-center">
                <i class="fas fa-star text-red-500 text-xs mr-px"></i>{{room.total_rating}}
            </span>
        </div>
        <span class="text-black w-11/12 block truncate">{{room.name}}</span>
    </a>
</div> 

templates/mixins/social_login.html
<div class="flex flex-col w-full">
    <a href = "{% url 'users:github-login' %}" class="btn border-2  text-gray-700 mb-2 border-gray-700">
        <i class="fab fa-github-alt mr-2 fa-lg"></i> Continue with Github
    </a>
    <a href = "{% url 'users:kakao-login' %}" class="btn border text-yellow-700 mb-2 border-yellow-400 bg-yellow-400" >
        <i class="fas fa-comment mr-2 fa-lg"></i> Continue with Kakao
    </a>
</div>  

<div class="flex items-center w-full my-5">
    <div class="h-px w-full bg-gray-400"></div>
    <span class="text-gray-700 font-medium mx-4 text-sm">or</span>
    <div class="h-px w-full bg-gray-400"></div>
</div>

templates/mixins/user_avatar.html
{% if user.avatar %}    
    <div class="{{h_and_w|default:'h-20 w-20'}} rounded-full bg-cover" style="background-image:url({{user.avatar.url}});">
{% else %}
    <div class="{{h_and_w|default:'h-20 w-20'}} bg-gray-700 rounded-full text-white flex justify-center items-center overflow-hidden">
        <span class="{{text|default:'text-3xl'}}">{{user.first_name|first}}</span>
    {% endif %}
</div>